### ISSUE TITLE
ProtoSpace挙動確認

### ISSUE THREAD

**Issue by aaaaaakjj** [aaaaaakjj/protospace-39781#2]
自身のProtoSpaceのURL（本番環境）

https://protospace-39781.onrender.com/

**Comment by yusuketono** [comment]
@aaaaaakjj さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
#### ユーザー管理機能
- [ ] **必要な情報を入力すると、ログインができること**
正しい情報を入力してもログインができません。
ログインが出来るように修正をお願いします。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by aaaaaakjj** [comment]
ユーザー管理機能
 必要な情報を入力すると、ログインができること
正しい情報を入力してもログインができません。
ログインが出来るように修正をお願いします。

を修正しました

**Comment by yusuketono** [comment]
@aaaaaakjj さん、再度ご提出ありがとうございます‼︎
LGTMとさせていただきます！

**Comment by aaaaaakjj** [comment]
確認テストありがとうございました。
